# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a920e5f0d8702735d61f6b642e2ccf1dbd484abf4ffa2462345acc020d26d10d39a2210b47a89ff52561a646ef5d85545f996f701a63dadf4dc9255ed2f4286a

test:
  secret_key_base: bae3f783633e327012fc7820dfd625dbb769429b9e565dc2f8e1ea11ab4acdb53875d6df64ca0f1a4e543504e7404e51f0d3294260fda072216f2d6883e58835

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
